export interface Product {
  id: string;
  title: string;
  category: "Jackets & Outerwear" | "Footwear" | "Backpacks & Luggage" | "Trail Equipment" | "Activewear" | "Accessories";
  price: number;
  rating: number; // 0.0 - 5.0
  reviewsCount: number;
  description: string;
  features: string[];
  semanticKeywords: string[];
  inStock: boolean;
  isPopular?: boolean;
  badge?: string;
}

export const PRODUCT_CATALOG: Product[] = [
  // --- Exact Spec Required Benchmark Products ---
  {
    id: "prod-01",
    title: "Weather Shield Trail Jacket",
    category: "Jackets & Outerwear",
    price: 189.99,
    rating: 4.8,
    reviewsCount: 342,
    description: "Engineered for high-altitude excursions in harsh weather. Features a triple-layer waterproof breathable membrane with thermal microfiber insulation and seam-sealed construction.",
    features: ["waterproof", "insulated", "outdoor use", "breathable 20k membrane", "fleece-lined storm collar"],
    semanticKeywords: ["warm", "jacket", "coat", "hiking", "trekking", "rain", "storm", "waterproof", "insulated", "fleece", "cold weather", "mountain", "outdoor use", "winter"],
    inStock: true,
    isPopular: true,
    badge: "Top Match",
  },
  {
    id: "prod-02",
    title: "AlpinePro Rain Shell",
    category: "Jackets & Outerwear",
    price: 135.00,
    rating: 4.6,
    reviewsCount: 215,
    description: "An ultralight emergency outer shell designed for fast-paced trail running and day treks when sudden downpours strike. Highly packable into its own chest pocket.",
    features: ["rain-resistant", "lightweight", "packable into chest pocket", "DWR nylon ripstop", "underarm ventilation zips"],
    semanticKeywords: ["rain", "jacket", "shell", "rain-resistant", "lightweight", "packable", "water resistant", "hiking", "trekking", "windbreaker", "downpour", "outdoor"],
    inStock: true,
    isPopular: true,
    badge: "Ultralight",
  },
  {
    id: "prod-03",
    title: "Summit Boreal Down Parka",
    category: "Jackets & Outerwear",
    price: 289.00,
    rating: 4.9,
    reviewsCount: 180,
    description: "Maximum sub-zero warmth featuring 800-fill responsible goose down with a hydrophobic treatment that repels freezing drizzle and sleet.",
    features: ["insulated", "heavyweight warmth", "water-repellent", "800 fill power", "detachable storm hood"],
    semanticKeywords: ["warm", "freezing", "down parka", "insulated", "winter", "heavy coat", "snow", "sleet", "arctic", "cozy", "extreme cold"],
    inStock: true,
    isPopular: true,
  },
  {
    id: "prod-04",
    title: "HydroVenture Storm Pants",
    category: "Jackets & Outerwear",
    price: 110.00,
    rating: 4.5,
    reviewsCount: 94,
    description: "Full-zip waterproof overtrousers that slip on over hiking boots during unexpected torrential rain on rugged mountain passes.",
    features: ["waterproof", "outdoor use", "full side zippers", "articulated knees", "abrasion resistant"],
    semanticKeywords: ["waterproof", "pants", "trousers", "rain", "hiking", "trail", "storm", "outdoor use", "dry"],
    inStock: true,
  },

  // --- Footwear ---
  {
    id: "prod-05",
    title: "TerraGrip Waterproof Hiking Boots",
    category: "Footwear",
    price: 165.00,
    rating: 4.7,
    reviewsCount: 420,
    description: "Ankle-support trail boot with eVent waterproof liner, Vibram lug outsole, and shock-absorbing EVA midsole for multi-day backpacking.",
    features: ["waterproof", "cushioned support", "outdoor use", "vibram grip", "ankle protection"],
    semanticKeywords: ["shoes", "boots", "footwear", "hiking", "trail", "waterproof", "mud", "walking", "backpacking", "ankle support", "outdoor use"],
    inStock: true,
    isPopular: true,
  },
  {
    id: "prod-06",
    title: "CloudStride All-Day Comfort Sneakers",
    category: "Footwear",
    price: 129.50,
    rating: 4.9,
    reviewsCount: 890,
    description: "Engineered specifically for professionals on their feet for 12+ hour shifts like nurses, doctors, and hospitality staff. Dual-density foam with non-slip tread.",
    features: ["ultra-cushioned", "slip-resistant", "orthopedic arch support", "breathable mesh", "machine washable"],
    semanticKeywords: ["shoes", "sneakers", "standing all day", "nurses", "hospital", "walking", "comfortable", "arch support", "cushioned", "non-slip", "work shoes"],
    inStock: true,
    isPopular: true,
    badge: "Bestseller",
  },
  {
    id: "prod-07",
    title: "AeroTrack Trail Running Shoes",
    category: "Footwear",
    price: 140.00,
    rating: 4.4,
    reviewsCount: 167,
    description: "Responsive, zero-drop off-road runners featuring quick-drying hydrophobic upper and aggressive 5mm multidirectional lugs for loose gravel.",
    features: ["lightweight", "quick-dry", "trail traction", "rock plate protection", "speed lacing"],
    semanticKeywords: ["running", "trail runner", "shoes", "sneakers", "lightweight", "quick drying", "gravel", "exercise", "outdoor"],
    inStock: true,
  },
  {
    id: "prod-08",
    title: "GlacierPeak Thermal Winter Boots",
    category: "Footwear",
    price: 195.00,
    rating: 4.8,
    reviewsCount: 142,
    description: "Insulated snow boots rated down to -25°F with Thinsulate lining and waterproof rubber shell for deep snow and icy winter trails.",
    features: ["insulated", "waterproof", "sub-zero rated", "deep snow traction", "shearling collar"],
    semanticKeywords: ["warm", "winter", "snow", "boots", "insulated", "ice", "freezing", "cold weather", "waterproof"],
    inStock: true,
  },

  // --- Backpacks & Luggage ---
  {
    id: "prod-09",
    title: "NomadTransit 35L Travel Backpack",
    category: "Backpacks & Luggage",
    price: 159.00,
    rating: 4.9,
    reviewsCount: 512,
    description: "Flight carry-on compliant travel pack featuring dedicated TSA flat-fold padded laptop compartment, concealed passport pocket, and waterproof Cordura canvas.",
    features: ["carry-on compliant", "padded laptop sleeve", "weatherproof", "lockable zips", "ergonomic harness"],
    semanticKeywords: ["bag", "backpack", "travel", "carry on", "laptop", "commute", "waterproof", "airplane", "weekend trip", "cabin", "luggage"],
    inStock: true,
    isPopular: true,
    badge: "Travel Pick",
  },
  {
    id: "prod-10",
    title: "DryVault 20L Submersible Dry Bag",
    category: "Backpacks & Luggage",
    price: 49.99,
    rating: 4.6,
    reviewsCount: 230,
    description: "Heavy-gauge 500D PVC roll-top waterproof sack that keeps electronics, clothing, and food completely dry even if dropped in rivers during kayaking or heavy rains.",
    features: ["100% waterproof", "roll-top buckle seal", "submersible", "outdoor use", "reflective trim"],
    semanticKeywords: ["waterproof", "dry bag", "kayak", "boating", "rain", "sack", "pouch", "submersible", "outdoor use", "river"],
    inStock: true,
  },
  {
    id: "prod-11",
    title: "TrailQuest 55L Internal Frame Pack",
    category: "Backpacks & Luggage",
    price: 219.00,
    rating: 4.7,
    reviewsCount: 310,
    description: "Multi-day expedition backpack with adjustable torso suspension, integrated rain cover, sleeping bag compartment, and hydration reservoir routing.",
    features: ["high capacity", "integrated rain cover", "weight distributing frame", "outdoor use", "trekking pole attachments"],
    semanticKeywords: ["hiking", "backpack", "trekking", "camping", "multiday", "outdoor use", "rain cover", "trail", "expedition"],
    inStock: true,
  },
  {
    id: "prod-12",
    title: "MetroCommute Waterproof Laptop Daypack",
    category: "Backpacks & Luggage",
    price: 89.00,
    rating: 4.5,
    reviewsCount: 188,
    description: "Slim, minimalist urban daypack made from seam-welded waterproof TPU fabric with a fleece-lined 16-inch laptop sleeve for rainy bike commutes.",
    features: ["waterproof", "laptop protection", "minimalist aesthetic", "bike commuter blinker loop", "hidden card pocket"],
    semanticKeywords: ["laptop", "bag", "backpack", "commute", "city", "bike", "waterproof", "rain", "work", "school", "minimalist"],
    inStock: true,
  },

  // --- Trail Equipment & Camping ---
  {
    id: "prod-13",
    title: "Solaris Ultralight 2-Person Backpacking Tent",
    category: "Trail Equipment",
    price: 279.00,
    rating: 4.8,
    reviewsCount: 198,
    description: "Freestanding sub-3lb double-wall tent with 3000mm hydrostatic head silicone rainfly, dual vestibules, and aircraft-grade aluminum poles.",
    features: ["waterproof rainfly", "ultralight under 3lbs", "outdoor use", "storm stable", "easy 3-minute pitch"],
    semanticKeywords: ["tent", "camping", "hiking", "outdoor use", "rain", "shelter", "sleep", "backpacking", "lightweight", "waterproof"],
    inStock: true,
  },
  {
    id: "prod-14",
    title: "EchoRest 20°F Synthetic Sleeping Bag",
    category: "Trail Equipment",
    price: 139.00,
    rating: 4.6,
    reviewsCount: 154,
    description: "Retains loft and thermal insulation even when damp from humidity or rain spray. Draft collar and contoured mummy hood lock in body warmth.",
    features: ["insulated", "warm down to 20F", "water-resistant shell", "retains heat when damp", "compression sack included"],
    semanticKeywords: ["warm", "sleeping bag", "insulated", "camping", "cold night", "hiking", "sleep", "thermal", "outdoor use"],
    inStock: true,
  },
  {
    id: "prod-15",
    title: "BlazeBeam 800-Lumen Waterproof Headlamp",
    category: "Trail Equipment",
    price: 39.95,
    rating: 4.7,
    reviewsCount: 620,
    description: "USB-C rechargeable head torch with IPX8 waterproof rating. Works in pouring rain with red night-vision mode and gesture sensor control.",
    features: ["IPX8 waterproof", "rechargeable", "red night light", "lightweight", "hands-free sensor"],
    semanticKeywords: ["flashlight", "headlamp", "light", "torch", "night", "hiking", "waterproof", "rain", "hands free", "camping"],
    inStock: true,
    isPopular: true,
  },
  {
    id: "prod-16",
    title: "CarbonPro Folding Trekking Poles",
    category: "Trail Equipment",
    price: 79.99,
    rating: 4.6,
    reviewsCount: 285,
    description: "100% carbon fiber 3-section folding hiking sticks with moisture-wicking natural cork grips and extended EVA sleeves for steep uphill traverses.",
    features: ["shock-absorbing", "collapsible", "cork grip", "outdoor use", "mud and snow baskets"],
    semanticKeywords: ["hiking sticks", "poles", "trekking", "walking", "knee support", "trail", "mountain", "outdoor use"],
    inStock: true,
  },

  // --- Activewear & Base Layers ---
  {
    id: "prod-17",
    title: "MerinoThermal 250 Base Layer Top",
    category: "Activewear",
    price: 95.00,
    rating: 4.9,
    reviewsCount: 312,
    description: "Pure 100% New Zealand merino wool long sleeve crew. Naturally odor-resistant, highly breathable, and provides natural warmth even when damp.",
    features: ["insulated", "moisture-wicking", "odor resistant", "natural merino warmth", "flatlock seams"],
    semanticKeywords: ["warm", "thermal", "base layer", "wool", "merino", "underwear", "hiking", "skiing", "winter", "cold weather", "cozy"],
    inStock: true,
    isPopular: true,
  },
  {
    id: "prod-18",
    title: "BreezeTech Quick-Dry Trail Tee",
    category: "Activewear",
    price: 38.00,
    rating: 4.5,
    reviewsCount: 175,
    description: "Featherlight athletic shirt engineered for hot summer climbs. Micro-perforated polyester disperses sweat instantly for rapid cooling.",
    features: ["sweat-wicking", "UPF 50+ sun protection", "lightweight", "anti-chafing", "rapid dry"],
    semanticKeywords: ["shirt", "t-shirt", "running", "hiking", "summer", "hot weather", "cooling", "breathable", "lightweight", "sweat wicking"],
    inStock: true,
  },
  {
    id: "prod-19",
    title: "StormProof Insulated Ski Mittens",
    category: "Activewear",
    price: 65.00,
    rating: 4.7,
    reviewsCount: 160,
    description: "Heavy-duty waterproof mittens lined with PrimaLoft Gold insulation and goat leather palm for brutal winter winds and snow.",
    features: ["waterproof", "insulated", "leather palm", "wrist leash", "extreme warmth"],
    semanticKeywords: ["gloves", "mittens", "hands", "warm", "insulated", "snow", "skiing", "winter", "freezing", "waterproof"],
    inStock: true,
  },

  // --- Accessories ---
  {
    id: "prod-20",
    title: "AquaPure Ultralight Trail Water Filter",
    category: "Accessories",
    price: 34.95,
    rating: 4.8,
    reviewsCount: 780,
    description: "Compact 0.1 micron hollow fiber membrane filter that removes 99.9999% of bacteria and protozoa from wild backcountry streams and lakes.",
    features: ["filters 100,000 gallons", "fits standard bottles", "ultralight 2oz", "outdoor use", "clean water"],
    semanticKeywords: ["water filter", "purifier", "drinking", "hiking", "camping", "survival", "outdoor use", "stream", "lake"],
    inStock: true,
    isPopular: true,
  },
  {
    id: "prod-21",
    title: "HydroSeal Phone Pouch with Lanyard",
    category: "Accessories",
    price: 19.99,
    rating: 4.6,
    reviewsCount: 440,
    description: "IPX8 certified clear waterproof phone case allowing full touchscreen photography underwater, in torrential downpours, or on fishing boats.",
    features: ["100% waterproof", "touchscreen responsive", "floating airbag rim", "lanyard included"],
    semanticKeywords: ["phone case", "waterproof", "rain", "beach", "boat", "swimming", "dry", "pouch", "submersible"],
    inStock: true,
  },
  {
    id: "prod-22",
    title: "PolarFleece Reversible Thermal Beanie",
    category: "Accessories",
    price: 24.00,
    rating: 4.7,
    reviewsCount: 290,
    description: "Dual-layer microfleece skull cap offering lightweight insulating warmth under climbing helmets or for crisp autumn morning hikes.",
    features: ["insulated", "fleece warmth", "helmet compatible", "snug fit", "wind resistant"],
    semanticKeywords: ["hat", "beanie", "warm", "fleece", "head", "winter", "cold weather", "hiking", "insulated"],
    inStock: true,
  },
  {
    id: "prod-23",
    title: "StormGuard Compact Trekking Umbrella",
    category: "Accessories",
    price: 42.00,
    rating: 4.4,
    reviewsCount: 118,
    description: "Reinforced fiberglass 8-rib frame with Teflon-coated 210T canopy that will not invert in 45mph mountain wind gusts. Folds to 10 inches.",
    features: ["rain-resistant", "windproof 45mph", "compact folding", "auto open-close", "lightweight"],
    semanticKeywords: ["umbrella", "rain", "storm", "windproof", "waterproof", "walking", "hiking", "portable", "compact"],
    inStock: true,
  },
];
